predictions:
	python src/openpose_3dpose_sandbox.py --residual --batch_norm --camera_frame --dropout 0.5 --max_norm --evaluateActionWise --use_sh --epochs 200 --sample --load 4874200 --openpose /root/dev/output/ --gif_fps 12
