predictions:
	python src/openpose_to_3d.py --residual --batch_norm --camera_frame --dropout 0.5 --max_norm --evaluateActionWise --use_sh --epochs 200 --sample --load 4874200 --openpose ../openpose/src/output/ --gif_fps 12
